# Generated by Django 5.2.7 on 2025-10-17 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.EmailField(max_length=50, unique=True)),
                ('date', models.DateField(max_length=30)),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=30)),
                ('available_seats', models.IntegerField()),
                ('event_type', models.CharField(choices=[('Webinar', 'Webinar'), ('Conference', 'Conference'), ('Workshop', 'Workshop'), ('Concert', 'Concert')], default='Webinar', max_length=15)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], max_length=15)),
                ('last_updated_on', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event_management.event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user_management.user')),
            ],
        ),
    ]
