# Generated by Django 5.2.7 on 2025-10-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.EmailField(max_length=50),
        ),
    ]
