# Generated by Django 5.2.7 on 2025-10-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0003_event_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
