# Generated by Django 5.2.7 on 2025-10-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Organizer', 'Organizer'), ('Attendee', 'Attendee'), ('Admin', 'Admin')], default='Attendee', max_length=15)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
