# Generated by Django 5.2.7 on 2025-10-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
