# Generated by Django 5.2.7 on 2025-10-20 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_user_username'),
        ('user_management', '0005_user_is_active_user_is_staff'),
    ]

    operations = [
    ]
