# Generated by Django 5.2.7 on 2025-10-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_user_username'),
        ('user_management', '0008_alter_user_username'),
    ]

    operations = [
    ]
